name: DEMO NTA Service API Spec file deployment
on:
  workflow_dispatch: 
    
jobs:
  setup-job:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout
       uses: actions/checkout@v4
       with:
        fetch-depth: 0
     - name: Determine environment
       id: determine-env
       run: |
          if [[ $GITHUB_REF == refs/heads/main ]]; then
             echo "environment=DEV" >> $GITHUB_OUTPUT
          elif [[ $GITHUB_REF == refs/heads/staging ]]; then
            echo "environment=TEST"  >> $GITHUB_OUTPUT
          else
            echo "environment=PROD"  >> $GITHUB_OUTPUT
          fi

  spec_automation:
    runs-on: ubuntu-latest
    needs: setup-job
    environment: ${{ needs.setup-job.outputs.environment }}
    env:
      OCI_CLI_USER: ${{ secrets.OCI_CLI_USER }}
      OCI_CLI_TENANCY: ${{ secrets.OCI_CLI_TENANCY }}
      OCI_CLI_FINGERPRINT: ${{ secrets.OCI_CLI_FINGERPRINT }}
      OCI_CLI_KEY_CONTENT: ${{ secrets.OCI_CLI_KEY_CONTENT }}
      OCI_CLI_REGION: ${{ secrets.OCI_CLI_REGION }}
    steps:
      - name: Running spec automation script
        run: |
            echo ${{ vars.COMPARTMENT_ID }} 
            echo ${{ vars.GATEWAY_ID }}
        shell: bash
