name: DEMO NTA Service API Spec file deployment
on:
  workflow_dispatch: 
    
jobs:
  spec_automation:
    runs-on: ubuntu-latest
    environment: DEV
    env:
      OCI_CLI_USER: ${{ secrets.OCI_CLI_USER }}
      OCI_CLI_TENANCY: ${{ secrets.OCI_CLI_TENANCY }}
      OCI_CLI_FINGERPRINT: ${{ secrets.OCI_CLI_FINGERPRINT }}
      OCI_CLI_KEY_CONTENT: ${{ secrets.OCI_CLI_KEY_CONTENT }}
      OCI_CLI_REGION: ${{ secrets.OCI_CLI_REGION }}
    steps:
     - name: Extract release name
       shell: bash
       run: echo "release=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" | cut -b 10-14 >> $GITHUB_OUTPUT
       id: extract_release
      
     - name: Running spec automation script
       run: |
            echo ${{ vars.COMPARTMENT_ID }} 
            echo ${{ vars.GATEWAY_ID }}
            echo ${{ steps.extract_release.outputs.release }}
       shell: bash
