name: DEMO NTA Service API Spec file deployment
on:
  push:
    branches:
       - main
  workflow_dispatch: 
    
jobs:
  spec_automation:
    runs-on: ubuntu-latest
    environment: DEV
    env:
      OCI_CLI_USER: ${{ secrets.OCI_CLI_USER }}
      OCI_CLI_TENANCY: ${{ secrets.OCI_CLI_TENANCY }}
      OCI_CLI_FINGERPRINT: ${{ secrets.OCI_CLI_FINGERPRINT }}
      OCI_CLI_KEY_CONTENT: ${{ secrets.OCI_CLI_KEY_CONTENT }}
      OCI_CLI_REGION: ${{ secrets.OCI_CLI_REGION }}
    steps:
     - name: Extract branch name
       shell: bash
       run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
       id: extract_branch
      
     - name: Retrieve the OCID of a named compartment in tenancy
       uses: oracle-actions/run-oci-cli-command@v1.1.1
       id: find-compartment-id
       with:
          command: 'iam compartment list --compartment-id-in-subtree=true'
          query: "data[?name=='testing'].id"
     - name: Running spec automation script
       run: |
            echo ${{ vars.COMPARTMENT_ID }} 
            echo ${{ vars.GATEWAY_ID }}
            echo ${{ steps.extract_branch.outputs.branch }}
       shell: bash
