on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/api_deployment.yaml@v1
        with:
          environment: dev
          # Other environment-specific inputs
